services:

  app:
    build: .
    container_name: cauldron-app

    network_mode: bridge

    ports:
      - "8008:8000"

    labels:
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/wizaarddlabs/cauldron/main/cauldron-removebg-preview.png"

    volumes:
      - ./app:/srv/app
      - ./data:/data

    environment:
      - REDIS_URL=redis://192.168.1.15:6380/0
      - ADDON_URL=${ADDON_URL:-http://localhost:8000}
      - ADDON_URL=${ADDON_URL:-http://localhost:8000}

    restart: unless-stopped


  redis:
    image: redis:7-alpine
    container_name: cauldron-redis

    network_mode: bridge

    ports:
      - "6380:6379"

    command: >
      sh -c "redis-server --maxmemory ${REDIS_MAX_MEMORY:-512mb} --maxmemory-policy ${REDIS_EVICTION_POLICY:-allkeys-lru}"

    restart: unless-stopped
