import asyncio
import logging
import time
from typing import Optional

import httpx
from fastapi import APIRouter, HTTPException, Request, Response
from fastapi.responses import RedirectResponse

from app.config import get_settings
from app.config_store import load_config
from app.debrid.factory import get_debrid_client
from app.models import CacheStatus, DebridProvider
from app.scrapers.aggregator import search_all


router = APIRouter()
logger = logging.getLogger(__name__)


CINEMETA_URL = (
    "https://v3-cinemeta.strem.io/meta/{type}/{id}.json"
)


# =========================================================
# PLAYBACK CACHE
# =========================================================
#
# Stremio can request the same playback URL multiple times.
# Without caching, every GET would:
#
#   1. Create a new Premiumize transfer
#   2. Poll Premiumize
#   3. Return another redirect
#
# Keep resolved playback URLs temporarily in memory.
#
# This is intentionally short because debrid playback URLs
# can expire.
# =========================================================

PLAYBACK_CACHE_TTL = 300  # 5 minutes

_playback_cache: dict[str, tuple[str, float]] = {}

_playback_locks: dict[str, asyncio.Lock] = {}

_playback_cache_lock = asyncio.Lock()


async def _get_playback_lock(key: str) -> asyncio.Lock:
    """
    Get a per-playback lock.

    This prevents multiple simultaneous Stremio requests
    from creating multiple transfers for the same torrent.
    """

    async with _playback_cache_lock:
        lock = _playback_locks.get(key)

        if lock is None:
            lock = asyncio.Lock()
            _playback_locks[key] = lock

        return lock


def _get_cached_playback_url(key: str) -> Optional[str]:
    """
    Return a cached playback URL if it is still valid.
    """

    cached = _playback_cache.get(key)

    if not cached:
        return None

    playback_url, expires_at = cached

    if time.monotonic() >= expires_at:
        _playback_cache.pop(key, None)
        return None

    return playback_url


def _cache_playback_url(
    key: str,
    playback_url: str,
) -> None:
    """
    Cache a resolved playback URL.
    """

    _playback_cache[key] = (
        playback_url,
        time.monotonic() + PLAYBACK_CACHE_TTL,
    )


# =========================================================
# MEDIA RESOLUTION
# =========================================================


async def resolve_media(type_: str, id_: str):
    imdb_id = id_
    season = None
    episode = None

    if type_ == "series" and ":" in id_:
        parts = id_.split(":")

        imdb_id = parts[0]

        if len(parts) >= 2:
            try:
                season = int(parts[1])
            except ValueError:
                season = None

        if len(parts) >= 3:
            try:
                episode = int(parts[2])
            except ValueError:
                episode = None

    url = CINEMETA_URL.format(
        type="movie" if type_ == "movie" else "series",
        id=imdb_id,
    )

    try:
        async with httpx.AsyncClient(
            timeout=15
        ) as client:
            response = await client.get(url)
            response.raise_for_status()
            data = response.json()

    except Exception as exc:
        logger.exception(
            "Failed to resolve Cinemeta metadata"
        )

        raise HTTPException(
            status_code=502,
            detail=f"Unable to resolve metadata: {exc}",
        )

    meta = data.get("meta") or {}

    title = meta.get("name") or meta.get("title")

    if not title:
        raise HTTPException(
            status_code=404,
            detail=f"Could not resolve title for {imdb_id}",
        )

    year = meta.get("year")

    try:
        year = int(year) if year else None
    except (TypeError, ValueError):
        year = None

    aliases = meta.get("aliases") or []

    logger.info("=== RESOLVED MEDIA ===")
    logger.info("Type: %s", type_)
    logger.info("IMDb: %s", imdb_id)
    logger.info("Title: %s", title)
    logger.info("Year: %s", year)
    logger.info("Aliases: %s", aliases)
    logger.info("Season: %s", season)
    logger.info("Episode: %s", episode)

    return {
        "type": type_,
        "imdb_id": imdb_id,
        "title": title,
        "year": year,
        "aliases": aliases,
        "season": season,
        "episode": episode,
    }


# =========================================================
# CONFIG
# =========================================================


def _decode_config(config: str):
    """
    Load the generated Stremio configuration from SQLite.

    The config value in the Stremio URL is the short ID
    generated by app.config_store.save_config().
    """

    cfg = load_config(config)

    if cfg is None:
        logger.error(
            "Configuration not found: %s",
            config,
        )

        raise HTTPException(
            status_code=404,
            detail=f"Configuration not found: {config}",
        )

    logger.info(
        "Loaded config %s",
        config,
    )

    logger.info(
        "Config provider: %s",
        cfg.get("provider"),
    )

    return cfg


def _normalize_debrid_config(cfg):
    """
    Normalize debrid configuration into:

        (provider, api_key)

    The generated Stremio configuration takes priority.
    """

    if cfg.get("provider") and cfg.get("api_key"):
        return (
            cfg["provider"],
            cfg["api_key"],
        )

    if cfg.get("torbox_key"):
        return (
            "torbox",
            cfg["torbox_key"],
        )

    if cfg.get("realdebrid_key"):
        return (
            "realdebrid",
            cfg["realdebrid_key"],
        )

    if cfg.get("alldebrid_key"):
        return (
            "alldebrid",
            cfg["alldebrid_key"],
        )

    if cfg.get("premiumize_key"):
        return (
            "premiumize",
            cfg["premiumize_key"],
        )

    if cfg.get("torrin_key"):
        return (
            "torrin",
            cfg["torrin_key"],
        )

    # -----------------------------------------------------
    # Application-level Torrin configuration
    # -----------------------------------------------------

    settings = get_settings()

    torrin_key = getattr(
        settings,
        "torrin_api_key",
        None,
    )

    if torrin_key:
        return (
            "torrin",
            torrin_key,
        )

    return None, None


# =========================================================
# CACHE LABEL
# =========================================================


def _cache_status_label(status):
    if status == CacheStatus.CACHED:
        return "⚡ Cached"

    if status == CacheStatus.NOT_CACHED:
        return "⏳ Uncached"

    return "❔ Unknown"


# =========================================================
# EXTERNAL URL
# =========================================================


def _external_base_url(request: Request) -> str:
    """
    Determine the externally reachable Cauldron URL.

    When Cauldron is behind Nginx Proxy Manager,
    X-Forwarded-Host / X-Forwarded-Proto are used.

    This prevents Stremio from receiving internal URLs
    such as:

        http://localhost:8000/...
    """

    forwarded_host = request.headers.get(
        "x-forwarded-host"
    )

    host = (
        forwarded_host
        or request.headers.get("host")
    )

    forwarded_proto = request.headers.get(
        "x-forwarded-proto"
    )

    proto = (
        forwarded_proto
        or request.url.scheme
    )

    if host:
        host = host.split(",")[0].strip()
        proto = proto.split(",")[0].strip()

        return (
            f"{proto}://{host}"
        ).rstrip("/")

    settings = get_settings()

    return settings.addon_url.rstrip("/")


# =========================================================
# STREAM
# =========================================================


@router.get("/{config}/stream/{type}/{id}.json")
async def stream(
    request: Request,
    config: str,
    type: str,
    id: str,
):
    logger.info("")
    logger.info(
        "========================================"
    )
    logger.info(
        "=== CAULDRON STREAM REQUEST ==="
    )
    logger.info(
        "TYPE: %s",
        type,
    )
    logger.info(
        "ID: %s",
        id,
    )
    logger.info(
        "CONFIG: %s",
        config,
    )
    logger.info(
        "========================================"
    )

    # -----------------------------------------------------
    # MEDIA TYPE
    # -----------------------------------------------------

    if type not in (
        "movie",
        "series",
    ):
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported media type: {type}",
        )

    # -----------------------------------------------------
    # MEDIA
    # -----------------------------------------------------

    media = await resolve_media(
        type,
        id,
    )

    logger.info(
        "SEARCHING: %s (%s) S%sE%s",
        media["title"],
        media["imdb_id"],
        media["season"],
        media["episode"],
    )

    # -----------------------------------------------------
    # CONFIG
    # -----------------------------------------------------

    cfg = _decode_config(config)

    provider_str, api_key = (
        _normalize_debrid_config(cfg)
    )

    debrid_client = None

    if provider_str and api_key:
        try:
            provider = DebridProvider(
                provider_str
            )

            debrid_client = (
                get_debrid_client(
                    provider,
                    api_key,
                )
            )

            logger.info(
                "Using debrid provider: %s",
                provider_str,
            )

        except Exception as exc:
            logger.warning(
                "Unable to initialize debrid "
                "provider %s: %s",
                provider_str,
                exc,
            )

    else:
        logger.info(
            "No debrid credentials configured"
        )

    # -----------------------------------------------------
    # SEARCH
    # -----------------------------------------------------

    try:
        results = await search_all(
            media["title"],
            imdb_id=media["imdb_id"],
            season=media["season"],
            episode=media["episode"],
            media_type=media["type"],
        )

    except Exception as exc:
        logger.exception(
            "Search failed"
        )

        raise HTTPException(
            status_code=500,
            detail=f"Search failed: {exc}",
        )

    logger.info(
        "SEARCH RESULTS: %d",
        len(results),
    )

    if not results:
        logger.info(
            "NO RESULTS"
        )

        return {
            "streams": []
        }

    # -----------------------------------------------------
    # CACHE CHECK
    # -----------------------------------------------------

    cache_status_map = {}

    if debrid_client:
        try:
            info_hashes = [
                str(
                    t.info_hash
                ).lower()
                for t in results
                if getattr(
                    t,
                    "info_hash",
                    None,
                )
            ]

            logger.info(
                "Checking %s cache status "
                "for %d hashes",
                provider_str,
                len(info_hashes),
            )

            if info_hashes:
                cache_status_map = (
                    await debrid_client.check_cache(
                        info_hashes
                    )
                )

                cached_count = sum(
                    1
                    for status
                    in cache_status_map.values()
                    if status
                    == CacheStatus.CACHED
                )

                uncached_count = sum(
                    1
                    for status
                    in cache_status_map.values()
                    if status
                    == CacheStatus.NOT_CACHED
                )

                unknown_count = (
                    len(info_hashes)
                    - cached_count
                    - uncached_count
                )

                logger.info(
                    "CACHE RESULTS: "
                    "%d cached / "
                    "%d uncached / "
                    "%d unknown / "
                    "%d total",
                    cached_count,
                    uncached_count,
                    unknown_count,
                    len(info_hashes),
                )

                for torrent in results:
                    info_hash = str(
                        getattr(
                            torrent,
                            "info_hash",
                            "",
                        )
                    ).lower()

                    status = (
                        cache_status_map.get(
                            info_hash,
                            CacheStatus.UNKNOWN,
                        )
                    )

                    logger.info(
                        "CACHE: %-12s | %s",
                        _cache_status_label(
                            status
                        ),
                        getattr(
                            torrent,
                            "title",
                            "unknown",
                        ),
                    )

        except Exception as exc:
            logger.exception(
                "Cache check failed: %s",
                exc,
            )

    # -----------------------------------------------------
    # EPISODE FILTERING
    # -----------------------------------------------------

    if (
        media["type"] == "series"
        and media["season"] is not None
        and media["episode"] is not None
    ):
        season = int(
            media["season"]
        )

        episode = int(
            media["episode"]
        )

        patterns = [
            f"s{season:02d}e{episode:02d}",
            f"s{season}e{episode}",
            f"{season}x{episode:02d}",
        ]

        filtered = []

        for torrent in results:
            torrent_title = str(
                getattr(
                    torrent,
                    "title",
                    "",
                )
            ).lower()

            if any(
                pattern.lower()
                in torrent_title
                for pattern in patterns
            ):
                filtered.append(
                    torrent
                )

        results = filtered

        logger.info(
            "AFTER EPISODE FILTER: %d",
            len(results),
        )

    # -----------------------------------------------------
    # CACHED ONLY
    # -----------------------------------------------------

    cached_only = cfg.get(
        "cached_only",
        False,
    )

    if (
        cached_only
        and debrid_client
    ):
        results = [
            torrent
            for torrent in results
            if cache_status_map.get(
                str(
                    torrent.info_hash
                ).lower(),
                CacheStatus.UNKNOWN,
            )
            == CacheStatus.CACHED
        ]

        logger.info(
            "AFTER CACHED-ONLY FILTER: %d",
            len(results),
        )

    # -----------------------------------------------------
    # FILTERING
    # -----------------------------------------------------

    try:
        from app.filtering.pipeline import (
            FilterPipeline
        )

        logger.info(
            "FILTER CONFIG - required_languages: %s",
            cfg.get("required_languages", [])
        )
        logger.info(
            "FILTER CONFIG - excluded_languages: %s",
            cfg.get("excluded_languages", [])
        )
        logger.info(
            "FILTER CONFIG - language: %s",
            cfg.get("language", [])
        )

        pipeline = FilterPipeline(
            cfg
        )

        results = pipeline.apply(
            results
        )

        logger.info(
            "AFTER FILTER PIPELINE: %d",
            len(results),
        )

    except Exception:
        logger.exception(
            "Filtering pipeline failed"
        )

    # -----------------------------------------------------
    # SORTING
    # -----------------------------------------------------

    try:
        from app.filtering.sorting import (
            sort_torrents
        )

        sort_criteria = cfg.get(
            "sort_criteria"
        )

        if isinstance(
            sort_criteria,
            str,
        ):
            sort_criteria = [
                value.strip()
                for value
                in sort_criteria.split(",")
                if value.strip()
            ]

        if not sort_criteria:
            sort_criteria = [
                "cached",
                "seeders",
                "resolution",
                "quality",
            ]

        sort_order = cfg.get(
            "sort_order",
            "desc",
        )

        allow_season_packs = (
            cfg.get(
                "allow_season_packs",
                False,
            )
        )

        results = sort_torrents(
            results,
            sort_criteria=sort_criteria,
            sort_order=sort_order,
            allow_season_packs=(
                allow_season_packs
            ),
            cache_status_map=(
                cache_status_map
            ),
        )

        logger.info(
            "AFTER SORTING: %d "
            "using %s %s",
            len(results),
            sort_criteria,
            sort_order,
        )

    except Exception:
        logger.exception(
            "Sorting failed"
        )

    # -----------------------------------------------------
    # BUILD STREAMS
    # -----------------------------------------------------

    streams = []

    base_url = _external_base_url(
        request
    )

    logger.info(
        "External base URL: %s",
        base_url,
    )

    for torrent in results:
        try:
            info_hash = str(
                getattr(
                    torrent,
                    "info_hash",
                    "",
                )
            ).lower()

            if not info_hash:
                logger.warning(
                    "Skipping torrent without "
                    "info hash: %s",
                    getattr(
                        torrent,
                        "title",
                        "unknown",
                    ),
                )

                continue

            cache_status = (
                cache_status_map.get(
                    info_hash,
                    CacheStatus.UNKNOWN,
                )
            )

            cache_label = (
                _cache_status_label(
                    cache_status
                )
            )

            quality = getattr(
                torrent,
                "quality",
                None,
            )

            indexer = getattr(
                torrent,
                "indexer",
                None,
            )

            seeders = getattr(
                torrent,
                "seeders",
                None,
            )

            size_bytes = getattr(
                torrent,
                "size_bytes",
                None,
            )

            # -------------------------------------------------
            # STREAM NAME
            # -------------------------------------------------

            name_parts = [
                "🧙 Cauldron"
            ]

            if indexer:
                name_parts.append(
                    str(indexer)
                )

            if quality:
                name_parts.append(
                    str(quality)
                )

            if debrid_client:
                name_parts.append(
                    cache_label
                )
            else:
                name_parts.append(
                    "P2P"
                )

            stream_name = (
                " • ".join(
                    name_parts
                )
            )

            # -------------------------------------------------
            # STREAM TITLE
            # -------------------------------------------------

            title_parts = [
                str(
                    getattr(
                        torrent,
                        "title",
                        "Unknown",
                    )
                )
            ]

            if quality:
                title_parts.append(
                    f"Quality: {quality}"
                )

            if seeders is not None:
                title_parts.append(
                    f"Seeds: {seeders}"
                )

            if size_bytes:
                try:
                    size_gb = (
                        float(size_bytes)
                        / (1024 ** 3)
                    )

                    if size_gb >= 1:
                        title_parts.append(
                            f"Size: "
                            f"{size_gb:.2f} GB"
                        )

                    else:
                        size_mb = (
                            float(size_bytes)
                            / (1024 ** 2)
                        )

                        title_parts.append(
                            f"Size: "
                            f"{size_mb:.0f} MB"
                        )

                except (
                    TypeError,
                    ValueError,
                ):
                    pass

            if debrid_client:
                title_parts.append(
                    f"Cache: {cache_label}"
                )

            # -------------------------------------------------
            # PLAYBACK URL
            # -------------------------------------------------

            if debrid_client:
                stream_url = (
                    f"{base_url}/"
                    f"{config}/playback/"
                    f"{info_hash}"
                )

                stream_data = {
                    "name": stream_name,
                    "title": "\n".join(
                        title_parts
                    ),
                    "url": stream_url,
                    "behaviorHints": {
                        "bingeGroup": (
                            "cauldron"
                        ),
                    },
                }

                logger.info(
                    "PLAYBACK URL: %s",
                    stream_url,
                )

            else:
                magnet = getattr(
                    torrent,
                    "magnet",
                    None,
                )

                stream_data = {
                    "name": stream_name,
                    "title": "\n".join(
                        title_parts
                    ),
                    "infoHash": info_hash,
                    "sources": (
                        [magnet]
                        if magnet
                        else []
                    ),
                    "behaviorHints": {
                        "bingeGroup": (
                            "cauldron"
                        ),
                    },
                }

            streams.append(
                stream_data
            )

            logger.info(
                "STREAM: %-30s | %s",
                stream_name,
                getattr(
                    torrent,
                    "title",
                    "unknown",
                ),
            )

        except Exception as exc:
            logger.exception(
                "Failed converting torrent "
                "to stream: %s",
                exc,
            )

    logger.info(
        "RETURNING STREAMS: %d",
        len(streams),
    )

    return {
        "streams": streams
    }


# =========================================================
# PLAYBACK
# =========================================================


@router.api_route(
    "/{config}/playback/{info_hash}",
    methods=["GET", "HEAD"],
)
async def playback(
    request: Request,
    config: str,
    info_hash: str,
):
    """
    Resolve a torrent hash through the configured
    debrid provider and redirect to its actual
    playback URL.

    HEAD requests are handled as lightweight
    availability checks and do not trigger
    debrid resolution.

    GET requests use an in-memory cache and per-hash
    locking to prevent duplicate debrid transfers.
    """

    logger.info("")
    logger.info(
        "========================================"
    )
    logger.info(
        "=== CAULDRON PLAYBACK REQUEST ==="
    )
    logger.info(
        "METHOD: %s",
        request.method,
    )
    logger.info(
        "CONFIG: %s",
        config,
    )
    logger.info(
        "HASH: %s",
        info_hash,
    )
    logger.info(
        "========================================"
    )

    # -----------------------------------------------------
    # LOAD CONFIG
    # -----------------------------------------------------

    cfg = _decode_config(
        config
    )

    provider_str, api_key = (
        _normalize_debrid_config(
            cfg
        )
    )

    if not provider_str:
        raise HTTPException(
            status_code=400,
            detail=(
                "No debrid provider "
                "configured"
            ),
        )

    if not api_key:
        raise HTTPException(
            status_code=400,
            detail=(
                "No debrid API key "
                "configured"
            ),
        )

    # -----------------------------------------------------
    # NORMALIZE HASH
    # -----------------------------------------------------

    info_hash = (
        info_hash
        .strip()
        .lower()
        .replace(
            "urn:btih:",
            "",
        )
    )

    if not info_hash:
        raise HTTPException(
            status_code=400,
            detail="Invalid torrent hash",
        )

    # -----------------------------------------------------
    # HEAD REQUEST
    # -----------------------------------------------------
    #
    # Stremio/proxies can issue HEAD before GET.
    #
    # Do NOT create a transfer here.
    # -----------------------------------------------------

    if request.method == "HEAD":
        logger.info(
            "HEAD playback check accepted"
        )

        return Response(
            status_code=200
        )

    # -----------------------------------------------------
    # PLAYBACK CACHE KEY
    # -----------------------------------------------------
    #
    # Include provider and config so different users
    # cannot accidentally share a cached URL.
    # -----------------------------------------------------

    cache_key = (
        f"{config}:"
        f"{provider_str}:"
        f"{info_hash}"
    )

    # -----------------------------------------------------
    # CHECK CACHE
    # -----------------------------------------------------

    cached_url = _get_cached_playback_url(
        cache_key
    )

    if cached_url:
        logger.info(
            "PLAYBACK CACHE HIT"
        )

        logger.info(
            "Provider: %s",
            provider_str,
        )

        logger.info(
            "Hash: %s",
            info_hash,
        )

        return RedirectResponse(
            url=cached_url,
            status_code=302,
        )

    logger.info(
        "PLAYBACK CACHE MISS"
    )

    # -----------------------------------------------------
    # PER-HASH LOCK
    # -----------------------------------------------------
    #
    # This is important when Stremio sends several GETs
    # at almost exactly the same time.
    #
    # Only the first request will contact Premiumize.
    # The others wait and then use the newly cached URL.
    # -----------------------------------------------------

    playback_lock = await _get_playback_lock(
        cache_key
    )

    async with playback_lock:

        # -------------------------------------------------
        # CHECK CACHE AGAIN
        # -------------------------------------------------
        #
        # Another request may have populated the cache
        # while we were waiting for the lock.
        # -------------------------------------------------

        cached_url = _get_cached_playback_url(
            cache_key
        )

        if cached_url:
            logger.info(
                "PLAYBACK CACHE HIT AFTER LOCK"
            )

            return RedirectResponse(
                url=cached_url,
                status_code=302,
            )

        # -------------------------------------------------
        # PROVIDER
        # -------------------------------------------------

        try:
            provider = DebridProvider(
                provider_str
            )

            debrid_client = (
                get_debrid_client(
                    provider,
                    api_key,
                )
            )

        except Exception as exc:
            logger.exception(
                "Unable to initialize "
                "debrid provider"
            )

            raise HTTPException(
                status_code=500,
                detail=(
                    f"Unable to initialize "
                    f"debrid provider: {exc}"
                ),
            )

        # -------------------------------------------------
        # MAGNET
        # -------------------------------------------------

        magnet = (
            f"magnet:?xt=urn:btih:"
            f"{info_hash}"
        )

        logger.info(
            "Resolving magnet: %s",
            magnet,
        )

        # -------------------------------------------------
        # ADD MAGNET
        # -------------------------------------------------

        try:
            torrent_id = (
                await debrid_client.add_magnet(
                    magnet
                )
            )

            logger.info(
                "Provider torrent ID: %s",
                torrent_id,
            )

        except Exception as exc:
            logger.exception(
                "Failed to add magnet to %s",
                provider_str,
            )

            raise HTTPException(
                status_code=502,
                detail=(
                    f"Failed to add torrent: "
                    f"{exc}"
                ),
            )

        # -------------------------------------------------
        # RESOLVE PLAYBACK
        # -------------------------------------------------

        last_error = None

        for attempt in range(15):
            try:
                resolved = (
                    await debrid_client.get_playback_link(
                        torrent_id
                    )
                )

                playback_url = getattr(
                    resolved,
                    "playback_url",
                    None,
                )

                if playback_url:
                    logger.info(
                        "PLAYBACK RESOLVED"
                    )

                    logger.info(
                        "Provider: %s",
                        provider_str,
                    )

                    logger.info(
                        "File: %s",
                        getattr(
                            resolved,
                            "file_name",
                            "unknown",
                        ),
                    )

                    # -----------------------------------------
                    # CACHE RESOLVED URL
                    # -----------------------------------------

                    _cache_playback_url(
                        cache_key,
                        playback_url,
                    )

                    logger.info(
                        "PLAYBACK URL CACHED "
                        "FOR %d SECONDS",
                        PLAYBACK_CACHE_TTL,
                    )

                    return RedirectResponse(
                        url=playback_url,
                        status_code=302,
                    )

                last_error = (
                    "Provider returned "
                    "no playback URL"
                )

            except Exception as exc:
                last_error = exc

                logger.info(
                    "Playback not ready "
                    "(attempt %d/15): %s",
                    attempt + 1,
                    exc,
                )

            if attempt < 14:
                await asyncio.sleep(2)

        logger.error(
            "Playback resolution failed "
            "after 30 seconds: %s",
            last_error,
        )

        raise HTTPException(
            status_code=504,
            detail=(
                f"Playback was not ready on "
                f"{provider_str}: "
                f"{last_error}"
            ),
        )
